services:
  nd_apps-shiny_serve:
    image: ghcr.io/endikau/nd_apps-shiny_serve:${ND_APPS_TAG:-latest}
    restart: unless-stopped
    ports:
      - "12347:3838"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
